wandb_version: 1

batch_size:
  desc: null
  value: 2
patch_size:
  desc: null
  value: 16
max_img_size:
  desc: null
  value: 2800
max_batch_tokens:
  desc: null
  value: 8100
n_bboxs:
  desc: null
  value: 100
dim_head:
  desc: null
  value: 64
n_heads:
  desc: null
  value: 2
dim:
  desc: null
  value: 1024
depth:
  desc: null
  value: 8
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1721425558
    t:
      1:
      - 1
      - 41
      - 49
      - 51
      - 55
      2:
      - 1
      - 41
      - 49
      - 51
      - 55
      3:
      - 16
      - 23
      4: 3.10.14
      5: 0.17.4
      8:
      - 4
      - 5
      13: darwin-arm64
